openapi: 3.0.3
info:
  title: Todo Tasks API
  description: RESTful API for task CRUD operations with JWT authentication and user isolation
  version: 1.0.0
  contact:
    name: API Support
    email: support@example.com

servers:
  - url: http://localhost:4000
    description: Development server
  - url: https://api.example.com
    description: Production server

security:
  - BearerAuth: []

paths:
  /api/{user_id}/tasks:
    get:
      summary: List all tasks for authenticated user
      description: Returns array of tasks belonging to authenticated user. User isolation enforced at query level.
      operationId: listTasks
      tags:
        - Tasks
      parameters:
        - name: user_id
          in: path
          required: true
          description: User ID (must match JWT token sub claim)
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Successfully retrieved tasks
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Task'
              example:
                - id: "123e4567-e89b-12d3-a456-426614174000"
                  user_id: "550e8400-e29b-41d4-a716-446655440000"
                  title: "Buy groceries"
                  description: "Milk, eggs, bread"
                  completed: false
                  created_at: "2026-01-29T10:00:00Z"
                  updated_at: "2026-01-29T10:00:00Z"
                - id: "223e4567-e89b-12d3-a456-426614174001"
                  user_id: "550e8400-e29b-41d4-a716-446655440000"
                  title: "Finish project"
                  description: null
                  completed: true
                  created_at: "2026-01-28T15:30:00Z"
                  updated_at: "2026-01-29T09:00:00Z"
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'

    post:
      summary: Create new task
      description: Creates a new task for authenticated user. Task ID and timestamps auto-generated.
      operationId: createTask
      tags:
        - Tasks
      parameters:
        - name: user_id
          in: path
          required: true
          description: User ID (must match JWT token sub claim)
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskCreate'
            example:
              title: "Buy groceries"
              description: "Milk, eggs, bread"
      responses:
        '201':
          description: Task created successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
              example:
                id: "123e4567-e89b-12d3-a456-426614174000"
                user_id: "550e8400-e29b-41d4-a716-446655440000"
                title: "Buy groceries"
                description: "Milk, eggs, bread"
                completed: false
                created_at: "2026-01-29T10:00:00Z"
                updated_at: "2026-01-29T10:00:00Z"
        '401':
          $ref: '#/components/responses/Unauthorized'
        '403':
          $ref: '#/components/responses/Forbidden'
        '422':
          $ref: '#/components/responses/ValidationError'

  /api/{user_id}/tasks/{id}:
    get:
      summary: Get single task by ID
      description: Returns specific task if it belongs to authenticated user. Returns 404 for unauthorized access to prevent enumeration.
      operationId: getTask
      tags:
        - Tasks
      parameters:
        - name: user_id
          in: path
          required: true
          description: User ID (must match JWT token sub claim)
          schema:
            type: string
            format: uuid
        - name: id
          in: path
          required: true
          description: Task ID
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Successfully retrieved task
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
              example:
                id: "123e4567-e89b-12d3-a456-426614174000"
                user_id: "550e8400-e29b-41d4-a716-446655440000"
                title: "Buy groceries"
                description: "Milk, eggs, bread"
                completed: false
                created_at: "2026-01-29T10:00:00Z"
                updated_at: "2026-01-29T10:00:00Z"
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
        '422':
          $ref: '#/components/responses/ValidationError'

    put:
      summary: Update task
      description: Updates task title and description. Preserves completed status. Auto-updates updated_at timestamp.
      operationId: updateTask
      tags:
        - Tasks
      parameters:
        - name: user_id
          in: path
          required: true
          description: User ID (must match JWT token sub claim)
          schema:
            type: string
            format: uuid
        - name: id
          in: path
          required: true
          description: Task ID
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskUpdate'
            example:
              title: "Buy organic groceries"
              description: "Whole Foods - milk, eggs, bread"
      responses:
        '200':
          description: Task updated successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
              example:
                id: "123e4567-e89b-12d3-a456-426614174000"
                user_id: "550e8400-e29b-41d4-a716-446655440000"
                title: "Buy organic groceries"
                description: "Whole Foods - milk, eggs, bread"
                completed: false
                created_at: "2026-01-29T10:00:00Z"
                updated_at: "2026-01-29T11:30:00Z"
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'
        '422':
          $ref: '#/components/responses/ValidationError'

    delete:
      summary: Delete task
      description: Permanently deletes task. Returns 404 for unauthorized access. Idempotent (returns 404 if already deleted).
      operationId: deleteTask
      tags:
        - Tasks
      parameters:
        - name: user_id
          in: path
          required: true
          description: User ID (must match JWT token sub claim)
          schema:
            type: string
            format: uuid
        - name: id
          in: path
          required: true
          description: Task ID
          schema:
            type: string
            format: uuid
      responses:
        '204':
          description: Task deleted successfully (no content)
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'

  /api/{user_id}/tasks/{id}/complete:
    patch:
      summary: Toggle task completion status
      description: Toggles completed status between true and false. Auto-updates updated_at timestamp.
      operationId: toggleTaskComplete
      tags:
        - Tasks
      parameters:
        - name: user_id
          in: path
          required: true
          description: User ID (must match JWT token sub claim)
          schema:
            type: string
            format: uuid
        - name: id
          in: path
          required: true
          description: Task ID
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Task completion status toggled successfully
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Task'
              example:
                id: "123e4567-e89b-12d3-a456-426614174000"
                user_id: "550e8400-e29b-41d4-a716-446655440000"
                title: "Buy groceries"
                description: "Milk, eggs, bread"
                completed: true
                created_at: "2026-01-29T10:00:00Z"
                updated_at: "2026-01-29T12:00:00Z"
        '401':
          $ref: '#/components/responses/Unauthorized'
        '404':
          $ref: '#/components/responses/NotFound'

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: JWT token from /api/auth/login endpoint

  schemas:
    Task:
      type: object
      required:
        - id
        - user_id
        - title
        - completed
        - created_at
        - updated_at
      properties:
        id:
          type: string
          format: uuid
          description: Unique task identifier (auto-generated)
          example: "123e4567-e89b-12d3-a456-426614174000"
        user_id:
          type: string
          format: uuid
          description: Owner user ID (from JWT token)
          example: "550e8400-e29b-41d4-a716-446655440000"
        title:
          type: string
          minLength: 1
          maxLength: 500
          description: Task title (required)
          example: "Buy groceries"
        description:
          type: string
          nullable: true
          description: Optional task description
          example: "Milk, eggs, bread"
        completed:
          type: boolean
          description: Completion status (default false)
          example: false
        created_at:
          type: string
          format: date-time
          description: Creation timestamp (auto-generated)
          example: "2026-01-29T10:00:00Z"
        updated_at:
          type: string
          format: date-time
          description: Last update timestamp (auto-updated)
          example: "2026-01-29T10:00:00Z"

    TaskCreate:
      type: object
      required:
        - title
      properties:
        title:
          type: string
          minLength: 1
          maxLength: 500
          description: Task title (required)
          example: "Buy groceries"
        description:
          type: string
          nullable: true
          description: Optional task description
          example: "Milk, eggs, bread"

    TaskUpdate:
      type: object
      required:
        - title
      properties:
        title:
          type: string
          minLength: 1
          maxLength: 500
          description: Task title (required)
          example: "Buy organic groceries"
        description:
          type: string
          nullable: true
          description: Optional task description
          example: "Whole Foods - milk, eggs, bread"

    Error:
      type: object
      required:
        - detail
      properties:
        detail:
          type: string
          description: Error message
          example: "Task not found"

    ValidationError:
      type: object
      required:
        - detail
      properties:
        detail:
          type: array
          items:
            type: object
            properties:
              loc:
                type: array
                items:
                  type: string
                description: Location of validation error
                example: ["body", "title"]
              msg:
                type: string
                description: Error message
                example: "Field required"
              type:
                type: string
                description: Error type
                example: "value_error.missing"

  responses:
    Unauthorized:
      description: Missing, invalid, or expired JWT token
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            detail: "Invalid token: Token expired"

    Forbidden:
      description: Valid token but user_id mismatch
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            detail: "Access denied: user_id mismatch"

    NotFound:
      description: Resource not found or unauthorized access (prevents enumeration)
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            detail: "Task not found"

    ValidationError:
      description: Request validation failed
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ValidationError'
          example:
            detail:
              - loc: ["body", "title"]
                msg: "Field required"
                type: "value_error.missing"

tags:
  - name: Tasks
    description: Task CRUD operations with user isolation
