"""add_scheduled_date_to_tasks

Revision ID: 16b04d3c6d04
Revises: a1f144b56eb6
Create Date: 2026-02-02 15:45:42.886937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '16b04d3c6d04'
down_revision: Union[str, None] = 'a1f144b56eb6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('scheduled_date', sa.Date(), nullable=True))
    op.create_index(op.f('ix_tasks_scheduled_date'), 'tasks', ['scheduled_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_tasks_scheduled_date'), table_name='tasks')
    op.drop_column('tasks', 'scheduled_date')
    # ### end Alembic commands ###
